#file: noinspection YAMLSchemaValidation
app:
  debug: true
  api: https://xxxx-api.local.uugoi.com
  log: C:/Code/Temp/go-boot/logs
port:
  api: 39898
  ws: 39899
data:
  mysql:
    host: docker.srv
    port: 3306
    database: go_boot_dev
    username: vity
    password: "P@ssw0rd"
    max-conn: 256
    max-idle: 4
    timeout: 60
  redis:
    host: docker.srv
    port: 6379
    database: 0
    username: ""
    password: ""
    max-conn: 16
    max-idle: 4
    timeout: 5
