#file: noinspection YAMLSchemaValidation
app:
  debug: true
  api: https://xxxx-api.local.uugoi.com
  log: C:/Code/Temp/go-boot/logs
port:
  api: 39898
  ws: 39899
data:
  mysql:
    dsn: "vity:P@ssw0rd@tcp(docker.srv:3306)/go_boot_dev?charset=utf8mb4&parseTime=True&loc=Local"
    max-open: 256
    max-idle: 4
    max-idle-time: 30
    max-conn-lifetime: 60
  redis:
    addr: docker.srv:6379
    database: 0
    username: ""
    password: ""
    min-idle: 2
    max-idle: 8
    prefix: GoBoot
